name: Tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  run-linters:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Set up dependencies
        run: npm install @google/clasp -g

      - name: Set up secret
        run: echo "${{ secret.clasprc }}" > /root/.clasprc.json

      - name: ...
        run: clasp clone 1YG8v2_a8Rs7Z0OJaMFcnQbh2pLO9Zg8PyWxyOrdGWyP0PMgvJD-BZdmJ

      - name: Install Node.js dependencies
        run: npm install --also=dev

      - name: Test
        run: npm test